# Generated by Django 2.2.5 on 2019-09-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={},
        ),
        migrations.AddField(
            model_name='film',
            name='cast',
            field=models.ManyToManyField(to='movie_list.Person'),
        ),
    ]
